### ISSUE TITLE
Shape Strokewidth type

### ISSUE THREAD

**Issue by goughjo02** [react-native-china/react-native-ART-doc#11]
In the React-Native-ART-doc (https://github.com/react-native-china/react-native-ART-doc/blob/master/doc.md), where it describes the api for `Shape`, it is said that the type of argument to be supplied to `StrokeWidth` is string, but in the example it is a number. Could anyone explain this?

by the way. I really appreciate this documentation. Many thanks.

**Comment by Obooman** [comment]
Thank you for figuring it out, both of them work.[Doc updated](https://github.com/react-native-china/react-native-ART-doc/commit/136960910fc4e72368ba47bf0361a6a63e381af7).
