### ISSUE TITLE
How to set click event of shape area in react native ? 

### ISSUE THREAD

**Issue by ap050492** [react-native-china/react-native-ART-doc#12]
Thanks for sharing this valuable documents...

I need write click event of particular Shape which draw using react native ART. How can i achieve this ?
can you please share your ideas or thought on this so can i worked on it.

Thanks all...

**Comment by Obooman** [comment]
For me, I wrap the whole `<Surface/>` within an `<View/>`, listen to View events and calculate the position to find out which "element" is the one being clicked on. take [this](https://stackoverflow.com/questions/9880279/how-do-i-add-a-simple-onclick-event-handler-to-a-canvas-element) as a reference.

**Comment by CezarCobuz** [comment]
Tried to wrap a `<Shape>` with a view, I am developing on web also. I get the following error:
> Uncaught Invariant Violation: ReactART does not support the type "div"

How did you resolve this?
