### ISSUE TITLE
ClippingRectangle Usage?

### ISSUE THREAD

**Issue by kylegoetz** [react-native-china/react-native-ART-doc#6]
Has anyone working on this (awesome) documentation figured out how exactly to get ClippingRectangle to work? I can't seem to figure it out. It appears to take props.children, so I figured you'd create something like `<ClippingRectangle ...><Shape .../></ClippingRectangle>` and it would clip the Shape, but when I try that, nothing gets rendered.

I tried setting CR's height to height/2 of the Surface's height and then stretching Shape to stretch the entire height of the Surface and then giving CR opacity={.5} figuring it'd make it easy to see where the clipping is taking place, but still just a blank canvas. If I remove the CR and just do the Shape, it gets rendered correctly.

Befuddling. Hopefully this isn't the wrong place to put this question. I tried looking all over the Internet for people discussing RN-ART and this is the first thing I found that had anything useful in it.

**Comment by Obooman** [comment]
Thanks for your response and I have updated [README.md](https://github.com/react-native-china/react-native-ART-doc/blob/master/doc.md#clippingrectangle) to add ClippingRectangle usage.Seems that you lose some properties.

I have tested it in `react-native@0.48`. if it doesn't work for you feel free to comment and I will recheck the platform version.
