### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by doublex** [react-native-china/react-native-ART-doc#7]
Could you give some information how to install ART?

````
console( React.ART )   ->  undefined
````

**Comment by Obooman** [comment]
Hi, this repo aims at usage so there's no content about linking ART library.

[Offical documentation](https://facebook.github.io/react-native/docs/linking-libraries-ios.html#step-1) teach you how to link a library and [Here is ART.xcodeproj](https://github.com/facebook/react-native/tree/master/Libraries/ART) project file,locally in your `node_modules/react-native/Libraries/ART`,
